#!/bin/bash

# Quick fix for missing migration 0029 - run this on your server

echo "🔧 Quick fix for migration 0029..."
echo ""

cd ~/GRA || { echo "❌ Not in GRA directory"; exit 1; }

echo "1. Creating missing migration 0029 file..."
mkdir -p engine/migrations

cat > engine/migrations/0029_alter_subscriptionplan_options_and_more.py << 'MIGRATION_EOF'
# Generated by Django - placeholder migration
# This migration resolves the missing 0029 reference in migration 0036

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0028_merge_subscription_models"),
    ]

    operations = [
        # Placeholder migration - no operations
        # The actual changes may have been applied directly to the database
    ]
MIGRATION_EOF

echo "✅ Created migration 0029 file"
echo ""

echo "2. Verifying file was created..."
if [ -f "engine/migrations/0029_alter_subscriptionplan_options_and_more.py" ]; then
    echo "✅ File exists: engine/migrations/0029_alter_subscriptionplan_options_and_more.py"
    ls -lh engine/migrations/0029*.py
else
    echo "❌ File creation failed!"
    exit 1
fi
echo ""

echo "3. Checking if migration 0029 is already applied in database..."
MIGRATION_STATUS=$(docker-compose exec -T web python manage.py showmigrations engine 2>/dev/null | grep "0029" || echo "")

if echo "$MIGRATION_STATUS" | grep -q "\[X\]"; then
    echo "⚠️  Migration 0029 is already applied in database"
    echo "   We'll fake it to mark it as applied"
    docker-compose exec -T web python manage.py migrate engine 0029 --fake 2>/dev/null || \
    docker-compose run --rm web python manage.py migrate engine 0029 --fake
    echo "✅ Migration 0029 faked"
else
    echo "Migration 0029 is not yet applied"
fi
echo ""

echo "4. Running migrations..."
docker-compose run --rm web python manage.py migrate 2>&1 | tail -20

echo ""
echo "5. Checking migration status..."
docker-compose exec -T web python manage.py showmigrations engine 2>/dev/null | grep -E "0028|0029|0030|0035|0036" || echo "Could not check status"

echo ""
echo "6. Restarting web container..."
docker-compose restart web

echo ""
echo "7. Waiting and checking logs..."
sleep 5
docker-compose logs --tail=15 web | tail -15

echo ""
echo "✅ Fix complete!"
echo ""
echo "If you still see errors, try:"
echo "  docker-compose exec web python manage.py migrate --fake-initial"
