# Generated by Django 5.2.6 on 2025-09-22 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dataset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("file_path", models.CharField(max_length=500)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="AnalysisSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("module", models.CharField(default="regression", max_length=100)),
                ("formula", models.TextField()),
                (
                    "analysis_type",
                    models.CharField(default="frequentist", max_length=20),
                ),
                ("options", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "heatmap_rel",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                (
                    "heatmap_table_rel",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                (
                    "spotlight_rel",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sessions",
                        to="engine.dataset",
                    ),
                ),
            ],
        ),
    ]
