# Generated by Django 5.2.6 on 2025-09-26 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0004_alter_analysissession_dataset"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="analysissession",
            name="heatmap_rel",
        ),
        migrations.RemoveField(
            model_name="analysissession",
            name="heatmap_table_rel",
        ),
    ]
