# Generated by Django 5.2.6 on 2025-09-30 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0005_remove_analysissession_heatmap_rel_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysissession",
            name="fitted_model",
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
