# Generated by Django 5.2.7 on 2025-11-01 22:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0009_subscriptionplan_analysissession_user_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly version of the title (e.g., 'about-us')",
                        max_length=200,
                        unique=True,
                    ),
                ),
                (
                    "page_type",
                    models.CharField(
                        choices=[
                            ("landing", "Landing Page"),
                            ("static", "Static Page"),
                            ("custom", "Custom Page"),
                        ],
                        default="static",
                        max_length=20,
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="HTML content for the page. Use rich text editor."
                    ),
                ),
                (
                    "meta_description",
                    models.CharField(
                        blank=True, help_text="SEO meta description", max_length=300
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True,
                        help_text="Unpublished pages won't be visible to public",
                    ),
                ),
                (
                    "is_default_landing",
                    models.BooleanField(
                        default=False,
                        help_text="Set as default landing page (only one can be active)",
                    ),
                ),
                (
                    "template_name",
                    models.CharField(
                        blank=True,
                        help_text="Optional custom template name",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_pages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_pages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Page",
                "verbose_name_plural": "Pages",
                "ordering": ["-updated_at"],
            },
        ),
    ]
