# Generated by Django 5.2.7 on 2025-11-02 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0010_page"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="allow_indexing",
            field=models.BooleanField(
                default=True, help_text="Allow search engines to index this page"
            ),
        ),
        migrations.AddField(
            model_name="page",
            name="canonical_url",
            field=models.URLField(
                blank=True,
                help_text="Canonical URL for SEO (prevents duplicate content issues)",
            ),
        ),
        migrations.AddField(
            model_name="page",
            name="follow_links",
            field=models.BooleanField(
                default=True,
                help_text="Allow search engines to follow links on this page",
            ),
        ),
        migrations.AddField(
            model_name="page",
            name="meta_keywords",
            field=models.CharField(
                blank=True,
                help_text="Comma-separated keywords for SEO (e.g., 'research, analysis, statistics')",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="page",
            name="meta_title",
            field=models.CharField(
                blank=True,
                help_text="Custom meta title for search engines (defaults to page title if empty)",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="page",
            name="og_description",
            field=models.TextField(
                blank=True,
                help_text="Description for social media sharing",
                max_length=300,
            ),
        ),
        migrations.AddField(
            model_name="page",
            name="og_image",
            field=models.URLField(
                blank=True,
                help_text="Image URL for social media sharing (recommended: 1200x630px)",
            ),
        ),
        migrations.AddField(
            model_name="page",
            name="og_title",
            field=models.CharField(
                blank=True,
                help_text="Title for social media sharing (defaults to page title)",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="page",
            name="og_type",
            field=models.CharField(
                default="website",
                help_text="Open Graph type (website, article, etc.)",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="page",
            name="meta_description",
            field=models.CharField(
                blank=True,
                help_text="SEO meta description (recommended: 150-160 characters)",
                max_length=300,
            ),
        ),
    ]
