# Generated by Django 5.2.7 on 2025-11-11 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0011_page_allow_indexing_page_canonical_url_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PrivacyPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.CharField(max_length=20, unique=True)),
                ("content", models.TextField()),
                ("effective_date", models.DateField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Privacy Policy",
                "verbose_name_plural": "Privacy Policies",
                "ordering": ["-effective_date"],
            },
        ),
        migrations.CreateModel(
            name="SubscriptionTierSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("free", "Free"),
                            ("low", "Low Tier (AI Basic)"),
                            ("mid", "Mid Tier (AI RAG)"),
                            ("high", "High Tier (AI Fine-tuned)"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "max_datasets",
                    models.IntegerField(
                        default=5,
                        help_text="Maximum number of datasets. Use -1 for unlimited.",
                    ),
                ),
                (
                    "max_sessions",
                    models.IntegerField(
                        default=10,
                        help_text="Maximum number of analysis sessions. Use -1 for unlimited.",
                    ),
                ),
                (
                    "max_file_size_mb",
                    models.IntegerField(
                        default=10,
                        help_text="Maximum file size in MB. Use -1 for unlimited.",
                    ),
                ),
                (
                    "ai_tier",
                    models.CharField(
                        choices=[
                            ("none", "No AI Access"),
                            ("general", "General Fine-tuned Model"),
                            ("rag", "RAG (Retrieval-Augmented Generation)"),
                            ("fine_tuned", "User Fine-tuned Model"),
                        ],
                        default="none",
                        help_text="AI access level for this tier",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Description of this tier"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Subscription Tier Settings",
                "verbose_name_plural": "Subscription Tier Settings",
                "ordering": ["tier"],
            },
        ),
        migrations.CreateModel(
            name="TermsOfService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.CharField(max_length=20, unique=True)),
                ("content", models.TextField()),
                ("effective_date", models.DateField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Terms of Service",
                "verbose_name_plural": "Terms of Service",
                "ordering": ["-effective_date"],
            },
        ),
        migrations.AlterModelOptions(
            name="subscriptionplan",
            options={"ordering": ["price_monthly"]},
        ),
        migrations.RemoveField(
            model_name="subscriptionplan",
            name="max_datasets",
        ),
        migrations.RemoveField(
            model_name="subscriptionplan",
            name="max_file_size_mb",
        ),
        migrations.RemoveField(
            model_name="subscriptionplan",
            name="max_sessions",
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="ai_features",
            field=models.JSONField(
                default=list, help_text="AI-specific features for this plan"
            ),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="tier_key",
            field=models.CharField(
                blank=True,
                help_text="Must match tier in SubscriptionTierSettings (free, low, mid, high)",
                max_length=20,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="ai_tier",
            field=models.CharField(
                choices=[
                    ("none", "No AI Access"),
                    ("general", "General Fine-tuned Model"),
                    ("rag", "RAG (Retrieval-Augmented Generation)"),
                    ("fine_tuned", "User Fine-tuned Model"),
                ],
                default="none",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionplan",
            name="features",
            field=models.JSONField(
                default=list,
                help_text="List of feature strings (e.g., ['AI Interpretation', 'RAG Support'])",
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionplan",
            name="price_monthly",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="subscriptionplan",
            name="price_yearly",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="max_datasets",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="max_file_size_mb",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="max_sessions",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="subscription_type",
            field=models.CharField(
                choices=[
                    ("free", "Free"),
                    ("low", "Low Tier (AI Basic)"),
                    ("mid", "Mid Tier (AI RAG)"),
                    ("high", "High Tier (AI Fine-tuned)"),
                ],
                default="free",
                max_length=20,
            ),
        ),
    ]
