# Generated by Django 5.2.7 on 2025-11-14 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0012_privacypolicy_subscriptiontiersettings_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("security", "Security Tests"),
                            ("database", "Database Tests"),
                            ("performance", "Performance Tests"),
                            ("unit", "Unit Tests"),
                            ("integration", "Integration Tests"),
                            ("api", "API Tests"),
                            ("e2e", "End-to-End Tests"),
                        ],
                        max_length=20,
                    ),
                ),
                ("test_name", models.CharField(max_length=200)),
                ("passed", models.BooleanField()),
                ("score", models.FloatField(blank=True, null=True)),
                ("total_tests", models.IntegerField()),
                ("passed_tests", models.IntegerField()),
                ("failed_tests", models.IntegerField()),
                ("execution_time", models.FloatField()),
                ("details", models.JSONField(default=dict)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["category", "-created_at"],
                        name="engine_test_categor_758dbd_idx",
                    ),
                    models.Index(
                        fields=["test_name", "-created_at"],
                        name="engine_test_test_na_c1abe1_idx",
                    ),
                ],
            },
        ),
    ]
