# Generated by Django 5.2.7 on 2025-11-14 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0013_testresult"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testresult",
            name="category",
            field=models.CharField(
                choices=[
                    ("security", "Security Tests"),
                    ("database", "Database Tests"),
                    ("performance", "Performance Tests"),
                    ("unit", "Unit Tests"),
                    ("integration", "Integration Tests"),
                    ("api", "API Tests"),
                    ("e2e", "End-to-End Tests"),
                    ("static_analysis", "Static Analysis Tests"),
                    ("dependency_scan", "Dependency Vulnerability Scan"),
                    ("coverage", "Coverage Check"),
                    ("backup", "Backup/Restore Tests"),
                    ("monitoring", "Monitoring/Logging Tests"),
                    ("cron", "Cron/Scheduled Task Tests"),
                    ("frontend", "Frontend Tests"),
                ],
                max_length=20,
            ),
        ),
    ]
