# Generated by Django 5.2.8 on 2025-11-16 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0014_alter_testresult_category"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIFineTuningFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name/description of the file", max_length=255
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="File to use for fine-tuning",
                        upload_to="ai_finetuning/files/",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of what this file contains"
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("training", "Training Data"),
                            ("validation", "Validation Data"),
                            ("prompt", "Prompt Template"),
                            ("system", "System Instructions"),
                            ("other", "Other"),
                        ],
                        default="training",
                        help_text="Type of file",
                        max_length=50,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this file is currently active",
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_finetuning_files",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Fine-tuning File",
                "verbose_name_plural": "AI Fine-tuning Files",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="AIFineTuningCommand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "command_type",
                    models.CharField(
                        choices=[
                            ("fine_tune", "Fine-tune Model"),
                            ("update_prompt", "Update System Prompt"),
                            ("add_context", "Add Context Data"),
                            ("test_model", "Test Model"),
                            ("reset_model", "Reset Model"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        default="fine_tune",
                        help_text="Type of command",
                        max_length=50,
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Description of what this command does"),
                ),
                (
                    "command_data",
                    models.JSONField(
                        default=dict,
                        help_text="JSON data for the command (e.g., parameters, file IDs, etc.)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "result",
                    models.TextField(
                        blank=True,
                        help_text="Result or error message from command execution",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_finetuning_commands",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "files",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Files associated with this command",
                        related_name="commands",
                        to="engine.aifinetuningfile",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Fine-tuning Command",
                "verbose_name_plural": "AI Fine-tuning Commands",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="aifinetuningfile",
            index=models.Index(
                fields=["-uploaded_at", "is_active"],
                name="engine_aifi_uploade_052dc6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="aifinetuningfile",
            index=models.Index(
                fields=["file_type", "is_active"], name="engine_aifi_file_ty_d32d80_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aifinetuningcommand",
            index=models.Index(
                fields=["-created_at", "status"], name="engine_aifi_created_104518_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aifinetuningcommand",
            index=models.Index(
                fields=["command_type", "status"], name="engine_aifi_command_2827a7_idx"
            ),
        ),
    ]
