# Generated by Django 5.2.8 on 2025-11-16 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0015_update_ai_finetuning_indexes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIFineTuningTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Name of the template", max_length=255),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of what this template is for"
                    ),
                ),
                (
                    "command_type",
                    models.CharField(
                        choices=[
                            ("fine_tune", "Fine-tune Model"),
                            ("update_prompt", "Update System Prompt"),
                            ("add_context", "Add Context Data"),
                            ("test_model", "Test Model"),
                            ("reset_model", "Reset Model"),
                            ("other", "Other"),
                        ],
                        help_text="Command type this template is for",
                        max_length=50,
                    ),
                ),
                (
                    "template_data",
                    models.JSONField(default=dict, help_text="JSON template data"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this template is active",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is the default template for this command type",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_finetuning_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Fine-tuning Template",
                "verbose_name_plural": "AI Fine-tuning Templates",
                "ordering": ["command_type", "name"],
                "indexes": [
                    models.Index(
                        fields=["command_type", "is_active"],
                        name="engine_aifi_command_6ddc30_idx",
                    ),
                    models.Index(
                        fields=["is_default", "command_type"],
                        name="engine_aifi_is_defa_ab65f3_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_default", True)),
                        fields=("command_type",),
                        name="unique_default_per_command_type",
                    )
                ],
            },
        ),
    ]
