# Generated by Django 5.2.8 on 2025-11-16 17:39

import engine.encrypted_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0016_add_ai_finetuning_templates"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="stripe_payment_intent_id",
            field=engine.encrypted_fields.EncryptedCharField(
                help_text="Encrypted Stripe payment intent ID", max_length=475
            ),
        ),
        migrations.AlterField(
            model_name="testresult",
            name="category",
            field=models.CharField(
                choices=[
                    ("security", "Security Tests"),
                    ("database", "Database Tests"),
                    ("performance", "Performance Tests"),
                    ("unit", "Unit Tests"),
                    ("integration", "Integration Tests"),
                    ("api", "API Tests"),
                    ("e2e", "End-to-End Tests"),
                    ("static_analysis", "Static Analysis Tests"),
                    ("dependency_scan", "Dependency Vulnerability Scan"),
                    ("coverage", "Coverage Check"),
                    ("backup", "Backup/Restore Tests"),
                    ("monitoring", "Monitoring/Logging Tests"),
                    ("cron", "Cron/Scheduled Task Tests"),
                    ("frontend", "Frontend Tests"),
                    ("privacy", "Privacy Compliance Tests"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="stripe_customer_id",
            field=engine.encrypted_fields.EncryptedCharField(
                blank=True,
                help_text="Encrypted Stripe customer ID",
                max_length=475,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="stripe_subscription_id",
            field=engine.encrypted_fields.EncryptedCharField(
                blank=True,
                help_text="Encrypted Stripe subscription ID",
                max_length=475,
                null=True,
            ),
        ),
    ]
