# Generated by Django 5.2.8 on 2025-11-16 18:26

import engine.encrypted_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0017_add_encrypted_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="stripe_payment_intent_id",
            field=engine.encrypted_fields.EncryptedCharField(
                help_text="Encrypted Stripe payment intent ID", max_length=475
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="stripe_customer_id",
            field=engine.encrypted_fields.EncryptedCharField(
                blank=True,
                help_text="Encrypted Stripe customer ID",
                max_length=475,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="stripe_subscription_id",
            field=engine.encrypted_fields.EncryptedCharField(
                blank=True,
                help_text="Encrypted Stripe subscription ID",
                max_length=475,
                null=True,
            ),
        ),
    ]
