# Generated by Django 5.2.8 on 2025-11-19 01:46

import django.db.models.deletion
import engine.encrypted_fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0021_alter_payment_stripe_payment_intent_id_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="stripe_payment_intent_id",
            field=engine.encrypted_fields.EncryptedCharField(
                help_text="Encrypted Stripe payment intent ID", max_length=475
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="stripe_customer_id",
            field=engine.encrypted_fields.EncryptedCharField(
                blank=True,
                help_text="Encrypted Stripe customer ID",
                max_length=475,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="stripe_subscription_id",
            field=engine.encrypted_fields.EncryptedCharField(
                blank=True,
                help_text="Encrypted Stripe subscription ID",
                max_length=475,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="AIProvider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name for this provider configuration (e.g., 'Production OpenAI', 'Development Claude')",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "provider_type",
                    models.CharField(
                        choices=[
                            ("openai", "OpenAI"),
                            ("anthropic", "Anthropic Claude"),
                            ("custom", "Custom API"),
                        ],
                        default="openai",
                        help_text="Type of AI provider",
                        max_length=50,
                    ),
                ),
                (
                    "api_key",
                    engine.encrypted_fields.EncryptedCharField(
                        help_text="API key for authentication (encrypted)",
                        max_length=1375,
                    ),
                ),
                (
                    "api_base_url",
                    models.URLField(
                        blank=True,
                        help_text="Base URL for API (optional, uses provider default if not set)",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "base_model",
                    models.CharField(
                        default="gpt-3.5-turbo",
                        help_text="Base model identifier (e.g., 'gpt-3.5-turbo', 'claude-3-opus')",
                        max_length=100,
                    ),
                ),
                (
                    "fine_tuned_model_id",
                    models.CharField(
                        blank=True,
                        help_text="ID of the fine-tuned model (if available)",
                        max_length=200,
                    ),
                ),
                (
                    "organization_id",
                    engine.encrypted_fields.EncryptedCharField(
                        blank=True,
                        help_text="Organization ID (for OpenAI, encrypted)",
                        max_length=700,
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this provider is currently active",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False, help_text="Whether this is the default provider"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "last_tested_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last time this provider was successfully tested",
                        null=True,
                    ),
                ),
                (
                    "test_status",
                    models.CharField(
                        choices=[
                            ("untested", "Untested"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        default="untested",
                        help_text="Status of last connection test",
                        max_length=20,
                    ),
                ),
                (
                    "test_message",
                    models.TextField(
                        blank=True, help_text="Message from last connection test"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created this configuration",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_providers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Provider",
                "verbose_name_plural": "AI Providers",
                "ordering": ["-is_default", "-is_active", "name"],
                "indexes": [
                    models.Index(
                        fields=["provider_type", "is_active"],
                        name="engine_aipr_provide_115f7a_idx",
                    ),
                    models.Index(
                        fields=["is_default", "is_active"],
                        name="engine_aipr_is_defa_8f8eaa_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_default", True)),
                        fields=("is_default",),
                        name="unique_default_provider",
                    )
                ],
            },
        ),
    ]
