# Generated by Django 5.2.8 on 2025-11-19 01:59

import django.db.models.deletion
import engine.encrypted_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0022_add_ai_provider_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="aifinetuningcommand",
            name="provider",
            field=models.ForeignKey(
                blank=True,
                help_text="AI provider to use for this command (uses default if not specified)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="commands",
                to="engine.aiprovider",
            ),
        ),
        migrations.AlterField(
            model_name="aiprovider",
            name="api_key",
            field=engine.encrypted_fields.EncryptedCharField(
                help_text="API key for authentication (encrypted)", max_length=1375
            ),
        ),
        migrations.AlterField(
            model_name="aiprovider",
            name="organization_id",
            field=engine.encrypted_fields.EncryptedCharField(
                blank=True,
                help_text="Organization ID (for OpenAI, encrypted)",
                max_length=700,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="stripe_payment_intent_id",
            field=engine.encrypted_fields.EncryptedCharField(
                help_text="Encrypted Stripe payment intent ID", max_length=475
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="stripe_customer_id",
            field=engine.encrypted_fields.EncryptedCharField(
                blank=True,
                help_text="Encrypted Stripe customer ID",
                max_length=475,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="stripe_subscription_id",
            field=engine.encrypted_fields.EncryptedCharField(
                blank=True,
                help_text="Encrypted Stripe subscription ID",
                max_length=475,
                null=True,
            ),
        ),
    ]
