# Generated by Django 5.2.8 on 2025-11-22 20:40

import engine.encrypted_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0023_add_provider_to_command"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "google_analytics_id",
                    models.CharField(
                        blank=True,
                        help_text="Google Analytics tracking ID (e.g., G-8FHJC3M9SD). Leave empty to disable.",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "google_analytics_code",
                    models.TextField(
                        blank=True,
                        help_text="Custom Google Analytics code (full script tags). If provided, this will be used instead of google_analytics_id.",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Enable/disable Google Analytics tracking",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Site Settings",
                "verbose_name_plural": "Site Settings",
            },
        ),
        migrations.AlterField(
            model_name="aiprovider",
            name="api_key",
            field=engine.encrypted_fields.EncryptedCharField(
                help_text="API key for authentication (encrypted)", max_length=1375
            ),
        ),
        migrations.AlterField(
            model_name="aiprovider",
            name="organization_id",
            field=engine.encrypted_fields.EncryptedCharField(
                blank=True,
                help_text="Organization ID (for OpenAI, encrypted)",
                max_length=700,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="stripe_payment_intent_id",
            field=engine.encrypted_fields.EncryptedCharField(
                help_text="Encrypted Stripe payment intent ID", max_length=475
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="stripe_customer_id",
            field=engine.encrypted_fields.EncryptedCharField(
                blank=True,
                help_text="Encrypted Stripe customer ID",
                max_length=475,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="stripe_subscription_id",
            field=engine.encrypted_fields.EncryptedCharField(
                blank=True,
                help_text="Encrypted Stripe subscription ID",
                max_length=475,
                null=True,
            ),
        ),
    ]
