# Generated by Django 5.2.8 on 2025-11-24 02:00

import django.db.models.deletion
import engine.encrypted_fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0024_add_site_settings"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="aiprovider",
            name="api_key",
            field=engine.encrypted_fields.EncryptedCharField(
                help_text="API key for authentication (encrypted)", max_length=1375
            ),
        ),
        migrations.AlterField(
            model_name="aiprovider",
            name="organization_id",
            field=engine.encrypted_fields.EncryptedCharField(
                blank=True,
                help_text="Organization ID (for OpenAI, encrypted)",
                max_length=700,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="stripe_payment_intent_id",
            field=engine.encrypted_fields.EncryptedCharField(
                help_text="Encrypted Stripe payment intent ID", max_length=475
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="stripe_customer_id",
            field=engine.encrypted_fields.EncryptedCharField(
                blank=True,
                help_text="Encrypted Stripe customer ID",
                max_length=475,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="stripe_subscription_id",
            field=engine.encrypted_fields.EncryptedCharField(
                blank=True,
                help_text="Encrypted Stripe subscription ID",
                max_length=475,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="AgentTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Unique name for this agent template (e.g., 'research_agent', 'sop_agent')",
                        max_length=200,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of what this agent template does",
                    ),
                ),
                (
                    "n8n_webhook_url",
                    models.URLField(
                        help_text="Full URL to the n8n webhook endpoint (e.g., http://localhost:5678/webhook/abc123)",
                        max_length=500,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("draft", "Draft"),
                        ],
                        default="draft",
                        help_text="Template status: active (usable), inactive (disabled), draft (in development)",
                        max_length=20,
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("internal", "Internal Only"),
                            ("customer_facing", "Customer Facing"),
                        ],
                        default="customer_facing",
                        help_text="Who can use this template: internal (staff only) or customer_facing (all users)",
                        max_length=20,
                    ),
                ),
                (
                    "mode_key",
                    models.CharField(
                        blank=True,
                        help_text="Optional: Chatbot mode key that maps to this template (e.g., 'research_agent'). If set, this template will be used when user selects this mode.",
                        max_length=100,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "default_parameters",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Default parameters to send to n8n webhook (JSON object)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this template",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_agent_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Agent Template",
                "verbose_name_plural": "Agent Templates",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status"], name="engine_agen_status_91ef49_idx"
                    ),
                    models.Index(
                        fields=["mode_key"], name="engine_agen_mode_ke_f2488a_idx"
                    ),
                    models.Index(
                        fields=["visibility"], name="engine_agen_visibil_a7a87f_idx"
                    ),
                ],
            },
        ),
    ]
