# Generated by Django 5.2.8 on 2025-11-25 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0028_merge_subscription_models"),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
