# Generated by Django 5.2.8 on 2025-11-25 20:02

from django.db import migrations, models


def add_updated_at_if_not_exists(apps, schema_editor):
    """Add updated_at field only if it doesn't already exist"""
    db_alias = schema_editor.connection.alias
    db_vendor = schema_editor.connection.vendor
    
    with schema_editor.connection.cursor() as cursor:
        # Check if column already exists (database-specific)
        column_exists = False
        if db_vendor == 'sqlite':
            cursor.execute("PRAGMA table_info(engine_subscriptionplan)")
            columns = [row[1] for row in cursor.fetchall()]
            column_exists = 'updated_at' in columns
        elif db_vendor == 'postgresql':
            cursor.execute("""
                SELECT EXISTS (
                    SELECT 1 
                    FROM information_schema.columns 
                    WHERE table_schema = 'public'
                    AND table_name = 'engine_subscriptionplan' 
                    AND column_name = 'updated_at'
                )
            """)
            column_exists = cursor.fetchone()[0]
        
        if not column_exists:
            # Column doesn't exist, add it
            if db_vendor == 'sqlite':
                cursor.execute("""
                    ALTER TABLE engine_subscriptionplan 
                    ADD COLUMN updated_at TIMESTAMP
                """)
            elif db_vendor == 'postgresql':
                cursor.execute("""
                    ALTER TABLE engine_subscriptionplan 
                    ADD COLUMN updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
                """)
                # Make it auto-update (PostgreSQL only)
                cursor.execute("""
                    CREATE OR REPLACE FUNCTION update_updated_at_column()
                    RETURNS TRIGGER AS $$
                    BEGIN
                        NEW.updated_at = NOW();
                        RETURN NEW;
                    END;
                    $$ language 'plpgsql';
                """)
                cursor.execute("""
                    CREATE TRIGGER update_engine_subscriptionplan_updated_at 
                    BEFORE UPDATE ON engine_subscriptionplan 
                    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column()
                """)


def reverse_add_updated_at(apps, schema_editor):
    """Remove updated_at field"""
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            DROP TRIGGER IF EXISTS update_engine_subscriptionplan_updated_at ON engine_subscriptionplan;
            ALTER TABLE engine_subscriptionplan DROP COLUMN IF EXISTS updated_at;
        """)


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0028_merge_subscription_models"),
    ]

    operations = [
        migrations.RunPython(
            add_updated_at_if_not_exists,
            reverse_add_updated_at,
        ),
        # Add field to Django's state (for model definition)
        migrations.AddField(
            model_name='subscriptionplan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
