# Generated by Django 5.2.8 on 2025-11-27 20:22

import django.db.models.deletion
import engine.encrypted_fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0031_remove_ai_tier"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subscriptionplan",
            options={
                "ordering": ["price_monthly"],
                "verbose_name": "Subscription Plan",
                "verbose_name_plural": "Subscription Plans",
            },
        ),
        migrations.AlterField(
            model_name="aiprovider",
            name="api_key",
            field=engine.encrypted_fields.EncryptedCharField(
                help_text="API key for authentication (encrypted)", max_length=1375
            ),
        ),
        migrations.AlterField(
            model_name="aiprovider",
            name="organization_id",
            field=engine.encrypted_fields.EncryptedCharField(
                blank=True,
                help_text="Organization ID (for OpenAI, encrypted)",
                max_length=700,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="stripe_payment_intent_id",
            field=engine.encrypted_fields.EncryptedCharField(
                help_text="Encrypted Stripe payment intent ID", max_length=475
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionplan",
            name="description",
            field=models.TextField(help_text="Description of this subscription plan"),
        ),
        migrations.AlterField(
            model_name="subscriptionplan",
            name="features",
            field=models.JSONField(
                default=list,
                help_text="List of feature strings displayed to users (e.g., ['AI Interpretation', 'RAG Support'])",
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionplan",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Whether this plan is available for purchase"
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionplan",
            name="price_monthly",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Monthly price in USD",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionplan",
            name="price_yearly",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Yearly price in USD (usually discounted)",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionplan",
            name="stripe_price_id_monthly",
            field=models.CharField(
                blank=True,
                help_text="Stripe Price ID for monthly billing",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionplan",
            name="stripe_price_id_yearly",
            field=models.CharField(
                blank=True,
                help_text="Stripe Price ID for yearly billing",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="max_datasets",
            field=models.IntegerField(
                blank=True,
                help_text="Override plan default. Null means use plan's max_datasets. Use -1 for unlimited.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="max_file_size_mb",
            field=models.IntegerField(
                blank=True,
                help_text="Override plan default. Null means use plan's max_file_size_mb. Use -1 for unlimited.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="max_sessions",
            field=models.IntegerField(
                blank=True,
                help_text="Override plan default. Null means use plan's max_sessions. Use -1 for unlimited.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="stripe_customer_id",
            field=engine.encrypted_fields.EncryptedCharField(
                blank=True,
                help_text="Encrypted Stripe customer ID",
                max_length=475,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="stripe_subscription_id",
            field=engine.encrypted_fields.EncryptedCharField(
                blank=True,
                help_text="Encrypted Stripe subscription ID",
                max_length=475,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="Paper",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the paper or project", max_length=200
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Optional description of the paper"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="papers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Paper",
                "verbose_name_plural": "Papers",
                "ordering": ["-updated_at"],
                "unique_together": {("name", "user")},
            },
        ),
        migrations.AddField(
            model_name="analysissession",
            name="paper",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional: Group this session into a paper/project",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sessions",
                to="engine.paper",
            ),
        ),
    ]
